apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: krb5kdc
  name: krb5kdc
  namespace: krb5ldap
spec:
  serviceName: krb5kdc
  replicas: 1
  template:
    metadata:
      labels:
        app: krb5kdc
    spec:
      containers:
      - name: krb5kdc
        image: tarusoopy/docker-kerberos
        envFrom:
        - configMapRef:
            name: krb5kdc-env
