apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5kdc-env
  namespace: nakano-a
data:
  REALM: "EDT.ORG"
  DOMAIN_REALM: "edt.org"
  KERB_MASTER_KEY: "admin"
  KERB_ADMIN_USER: "admin"
  KERB_ADMIN_PASS: "admin"
  SEARCH_DOMAINS: "edt.org"
  NAMESERVER_IP: "172.16.0.1"
  LDAPSERVER: "ldap"
  BASE_DC: "dc=edt,dc=org"
